/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for making a custom color palette to use in the Red DF website.
 */
export interface ColorPaletteSchema {
  /**
   * A color object containing different shades.
   *
   * This interface was referenced by `ColorPaletteSchema`'s JSON-Schema definition
   * via the `patternProperty` "^[A-Z]+$".
   */
  [k: string]: {
    /**
     * 4th dark shade of the color.
     */
    DARK_4?: {
      [k: string]: unknown;
    };
    /**
     * 3rd dark shade of the color.
     */
    DARK_3?: {
      [k: string]: unknown;
    };
    /**
     * 2nd dark shade of the color.
     */
    DARK_2?: {
      [k: string]: unknown;
    };
    /**
     * 1st dark shade of the color.
     */
    DARK_1?: {
      [k: string]: unknown;
    };
    /**
     * Neutral shade of the color.
     */
    NEUTRAL: {
      [k: string]: unknown;
    };
    /**
     * 1st light shade of the color.
     */
    LIGHT_1?: {
      [k: string]: unknown;
    };
    /**
     * 2nd light shade of the color.
     */
    LIGHT_2?: {
      [k: string]: unknown;
    };
    /**
     * 3rd light shade of the color.
     */
    LIGHT_3?: {
      [k: string]: unknown;
    };
    /**
     * 4th light shade of the color.
     */
    LIGHT_4?: {
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
}
